#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominikSlawkowskiLab4___zad_dom
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Wypożyczalnia_samochodów")]
	public partial class DataClassesDocumentsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUczniowie(Uczniowie instance);
    partial void UpdateUczniowie(Uczniowie instance);
    partial void DeleteUczniowie(Uczniowie instance);
    partial void InsertUwagi_uczniów(Uwagi_uczniów instance);
    partial void UpdateUwagi_uczniów(Uwagi_uczniów instance);
    partial void DeleteUwagi_uczniów(Uwagi_uczniów instance);
    #endregion
		
		public DataClassesDocumentsDataContext() : 
				base(global::DominikSlawkowskiLab4___zad_dom.Properties.Settings.Default.Wypożyczalnia_samochodówConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocumentsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocumentsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocumentsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDocumentsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Oceny_ucznia_1> Oceny_ucznia_1s
		{
			get
			{
				return this.GetTable<Oceny_ucznia_1>();
			}
		}
		
		public System.Data.Linq.Table<Oceny_ucznia_2> Oceny_ucznia_2s
		{
			get
			{
				return this.GetTable<Oceny_ucznia_2>();
			}
		}
		
		public System.Data.Linq.Table<Oceny_ucznia_3> Oceny_ucznia_3s
		{
			get
			{
				return this.GetTable<Oceny_ucznia_3>();
			}
		}
		
		public System.Data.Linq.Table<Uczniowie> Uczniowies
		{
			get
			{
				return this.GetTable<Uczniowie>();
			}
		}
		
		public System.Data.Linq.Table<Uwagi_uczniów> Uwagi_ucznióws
		{
			get
			{
				return this.GetTable<Uwagi_uczniów>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Oceny ucznia 1]")]
	public partial class Oceny_ucznia_1
	{
		
		private int _ID;
		
		private int _Matematyka;
		
		private int _Język_polski;
		
		private int _Przyroda;
		
		public Oceny_ucznia_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matematyka", DbType="Int NOT NULL")]
		public int Matematyka
		{
			get
			{
				return this._Matematyka;
			}
			set
			{
				if ((this._Matematyka != value))
				{
					this._Matematyka = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Język polski]", Storage="_Język_polski", DbType="Int NOT NULL")]
		public int Język_polski
		{
			get
			{
				return this._Język_polski;
			}
			set
			{
				if ((this._Język_polski != value))
				{
					this._Język_polski = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Przyroda", DbType="Int NOT NULL")]
		public int Przyroda
		{
			get
			{
				return this._Przyroda;
			}
			set
			{
				if ((this._Przyroda != value))
				{
					this._Przyroda = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Oceny ucznia 2]")]
	public partial class Oceny_ucznia_2
	{
		
		private int _ID;
		
		private int _Matematyka;
		
		private int _Język_polski;
		
		private int _Przyroda;
		
		public Oceny_ucznia_2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matematyka", DbType="Int NOT NULL")]
		public int Matematyka
		{
			get
			{
				return this._Matematyka;
			}
			set
			{
				if ((this._Matematyka != value))
				{
					this._Matematyka = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Język polski]", Storage="_Język_polski", DbType="Int NOT NULL")]
		public int Język_polski
		{
			get
			{
				return this._Język_polski;
			}
			set
			{
				if ((this._Język_polski != value))
				{
					this._Język_polski = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Przyroda", DbType="Int NOT NULL")]
		public int Przyroda
		{
			get
			{
				return this._Przyroda;
			}
			set
			{
				if ((this._Przyroda != value))
				{
					this._Przyroda = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Oceny ucznia 3]")]
	public partial class Oceny_ucznia_3
	{
		
		private int _ID;
		
		private int _Matematyka;
		
		private int _Język_polski;
		
		private int _Przyroda;
		
		public Oceny_ucznia_3()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matematyka", DbType="Int NOT NULL")]
		public int Matematyka
		{
			get
			{
				return this._Matematyka;
			}
			set
			{
				if ((this._Matematyka != value))
				{
					this._Matematyka = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Język polski]", Storage="_Język_polski", DbType="Int NOT NULL")]
		public int Język_polski
		{
			get
			{
				return this._Język_polski;
			}
			set
			{
				if ((this._Język_polski != value))
				{
					this._Język_polski = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Przyroda", DbType="Int NOT NULL")]
		public int Przyroda
		{
			get
			{
				return this._Przyroda;
			}
			set
			{
				if ((this._Przyroda != value))
				{
					this._Przyroda = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uczniowie")]
	public partial class Uczniowie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Imię;
		
		private string _Nazwisko;
		
		private string _Klasa;
		
		private EntityRef<Uwagi_uczniów> _Uwagi_uczniów;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImięChanging(string value);
    partial void OnImięChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnKlasaChanging(string value);
    partial void OnKlasaChanged();
    #endregion
		
		public Uczniowie()
		{
			this._Uwagi_uczniów = default(EntityRef<Uwagi_uczniów>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imię", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Imię
		{
			get
			{
				return this._Imię;
			}
			set
			{
				if ((this._Imię != value))
				{
					this.OnImięChanging(value);
					this.SendPropertyChanging();
					this._Imię = value;
					this.SendPropertyChanged("Imię");
					this.OnImięChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klasa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Klasa
		{
			get
			{
				return this._Klasa;
			}
			set
			{
				if ((this._Klasa != value))
				{
					this.OnKlasaChanging(value);
					this.SendPropertyChanging();
					this._Klasa = value;
					this.SendPropertyChanged("Klasa");
					this.OnKlasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uczniowie_Uwagi_uczniów", Storage="_Uwagi_uczniów", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public Uwagi_uczniów Uwagi_uczniów
		{
			get
			{
				return this._Uwagi_uczniów.Entity;
			}
			set
			{
				Uwagi_uczniów previousValue = this._Uwagi_uczniów.Entity;
				if (((previousValue != value) 
							|| (this._Uwagi_uczniów.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uwagi_uczniów.Entity = null;
						previousValue.Uczniowie = null;
					}
					this._Uwagi_uczniów.Entity = value;
					if ((value != null))
					{
						value.Uczniowie = this;
					}
					this.SendPropertyChanged("Uwagi_uczniów");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Uwagi uczniów]")]
	public partial class Uwagi_uczniów : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Uwagi;
		
		private EntityRef<Uczniowie> _Uczniowie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUwagiChanging(string value);
    partial void OnUwagiChanged();
    #endregion
		
		public Uwagi_uczniów()
		{
			this._Uczniowie = default(EntityRef<Uczniowie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._Uczniowie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uwagi", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Uwagi
		{
			get
			{
				return this._Uwagi;
			}
			set
			{
				if ((this._Uwagi != value))
				{
					this.OnUwagiChanging(value);
					this.SendPropertyChanging();
					this._Uwagi = value;
					this.SendPropertyChanged("Uwagi");
					this.OnUwagiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uczniowie_Uwagi_uczniów", Storage="_Uczniowie", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Uczniowie Uczniowie
		{
			get
			{
				return this._Uczniowie.Entity;
			}
			set
			{
				Uczniowie previousValue = this._Uczniowie.Entity;
				if (((previousValue != value) 
							|| (this._Uczniowie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uczniowie.Entity = null;
						previousValue.Uwagi_uczniów = null;
					}
					this._Uczniowie.Entity = value;
					if ((value != null))
					{
						value.Uwagi_uczniów = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("Uczniowie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
